server:
  port: 9537

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: eureka-client-01