server:
  port: 9629

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9527/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true #\u8BBF\u95EE\u8DEF\u52B2\u53EF\u73B0\u5B9Eip\u5730\u5740
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

info:
  author.name: huangxc
  app.name: ${spring.application.name}
  server.port: ${server.port}
  application.name: ${spring.application.name}

zuul:
  ignored-services: "*"  # \u4E0D\u5141\u8BB8\u7528\u5FAE\u670D\u52A1\u540D\u8BBF\u95EE\u4E86\uFF0C\u5982\u679C\u7981\u7528\u6240\u6709\u7684\uFF0C\u53EF\u4EE5\u4F7F\u7528 "*"
  routes:
    prefix: /zuul # \u7ED9\u8DEF\u7531\u52A0\u4E00\u4E2A\u7EDF\u4E00\u7684\u524D\u7F00
    # \u5982\u4E0B\u6307\u5B9A\u65B0\u7684\u6620\u5C04
    user:
      serviceId: user
      path: /user/**
    movie:
      serviceId: movie
      path: /movie/**

  host:
    connect-timeout-millis: 15000  #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 60000  #socket超时时间
  ribbon-isolation-strategy: semaphore
  semaphore:
    max-semaphores: 20


