server:
  port: 9529

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9528/eureka/

spring:
  application:
    name: eureka-server-03