server:
  port: 9538

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PangZiShenTiHao/configFile
          search-paths: config-repo
          username: PangZiShenTiHao
          password: Pang1023
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"


#security:                       #是否开启基本的鉴权，默认为true
  #basic:
    #enabled: false

