server:
  port: 9538

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PangZiShenTiHao/configFile
          search-paths: config-repo
          username: PangZiShenTiHao
          password: Pang1023
      label: master
